export const LOAD_TRAINEE_PROFILE_SUCCESS = "LOAD_TRAINEE_PROFILE_SUCCESS";
export const LOAD_TRAINEE_PROFILE_FAILURE = "LOAD_TRAINEE_PROFILE_FAILURE";

export const LOAD_REFERENCE_GENDER_SUCCESS = "LOAD_REFERENCE_GENDER_SUCCESS";
export const LOAD_REFERENCE_GENDER_FAILURE = "LOAD_REFERENCE_GENDER_FAILURE";
export const LOAD_REFERENCE_COLLEGES_SUCCESS =
  "LOAD_REFERENCE_COLLEGES_SUCCESS";
export const LOAD_REFERENCE_COLLEGES_FAILURE =
  "LOAD_REFERENCE_COLLEGES_FAILURE";

export const LOAD_REFERENCE_DESIGNATED_BODIES_SUCCESS =
  "LOAD_REFERENCE_DESIGNATED_BODIES_SUCCESS";
export const LOAD_REFERENCE_DESIGNATED_BODIES_FAILURE =
  "LOAD_REFERENCE_DESIGNATED_BODIES_FAILURE";

export const LOAD_REFERENCE_LOCAL_OFFICES_SUCCESS =
  "LOAD_REFERENCE_LOCAL_OFFICES_SUCCESS";
export const LOAD_REFERENCE_LOCAL_OFFICES_FAILURE =
  "LOAD_REFERENCE_LOCAL_OFFICES_FAILURE";
export const LOAD_REFERENCE_GRADES_SUCCESS = "LOAD_REFERENCE_GRADES_SUCCESS";
export const LOAD_REFERENCE_GRADES_FAILURE = "LOAD_REFERENCE_GRADES_FAILURE";
export const LOAD_REFERENCE_IMMIGRATION_STATUS_SUCCESS =
  "LOAD_REFERENCE_IMMIGRATION_STATUS_SUCCESS";
export const LOAD_REFERENCE_IMMIGRATION_STATUS_FAILURE =
  "LOAD_REFERENCE_IMMIGRATION_STATUS_FAILURE";
export const LOAD_REFERENCE_CURRICULA_SUCCESS =
  "LOAD_REFERENCE_CURRICULA_SUCCESS";
export const LOAD_REFERENCE_CURRICULA_FAILURE =
  "LOAD_REFERENCE_CURRICULA_FAILURE";

export const LOADING_FORMR_PARTA_LIST = "LOADING_FORMR_PARTA_LIST";
export const LOAD_FORMR_PARTA_LIST_SUCCESS = "LOAD_FORMR_PARTA_LIST_SUCCESS";
export const LOAD_FORMR_PARTA_LIST_FAILURE = "LOAD_FORMR_PARTA_LIST_FAILURE";
export const LOAD_FORMR_PARTA_SUCCESS = "LOAD_FORMR_PARTA_SUCCESS";
export const LOAD_FORMR_PARTA_FAILURE = "LOAD_FORMR_PARTA_FAILURE";
export const UPDATE_FORMR_PARTA = "UPDATE_FORMR_PARTA";

export const LOADING_FORMR_PARTB_LIST = "LOADING_FORMR_PARTB_LIST";
export const LOAD_FORMR_PARTB_LIST_SUCCESS = "LOAD_FORMR_PARTB_LIST_SUCCESS";
export const LOAD_FORMR_PARTB_LIST_FAILURE = "LOAD_FORMR_PARTB_LIST_FAILURE";
export const INITIALIZE_FORMR_PARTB_SUCCESS = "INITIALIZE_FORMR_PARTB_SUCCESS";
export const INITIALIZE_FORMR_PARTB_FAILURE = "INITIALIZE_FORMR_PARTB_FAILURE";
export const EDIT_FORMR_PARTB = "EDIT_FORMR_PARTB";
export const LOAD_FORMR_PARTB = "LOAD_FORMR_PARTB";
export const MOVE_TO_SECTION = "MOVE_TO_SECTION";

export const LOAD_FEATURE_FLAGS_SUCCESS = "LOAD_FEATURE_FLAGS_SUCCESS";
export const LOAD_FEATURE_FLAGS_FAILURE = "LOAD_FEATURE_FLAGS_FAILURE";
